package main.web.services.fitsense.challenge.domain.model.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.util.Date;

/**
 * Represents a personalized routine (generated by AI) assigned to a user.
 * Data of the exercises is stored in the JSON (rutina_json).
 *
 * @author Fiorella
 * @version 1.2
 */
@Getter
@Setter
@Entity
@Table(name = "rutinas")
public class Challenge {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String userId;

    @Lob
    @Column(name = "plan_json", columnDefinition = "TEXT", nullable = false)
    private String rutinaJson;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, updatable = false)
    private Date createdAt = new Date();

    public Challenge() {}

    public Challenge(String userId, String rutinaJson) {
        this.userId = userId;
        this.rutinaJson = rutinaJson;
    }
}
