package main.web.services.fitsense.challenge.rest.resources;

/**
 * Represents the data returned when fetching a user's personalized routine (Challenge).
 * The routine is stored as JSON (rutina_json) generated by the AI.
 *
 * @author Fiorella
 */
public record ChallengeResource(Long id, String userId, Object rutinaJson) {}

